
services:
  db: 
    image: postgres:16
    container_name: json_share_db
    restart: always
    environment:
      POSTGRES_USER: amen
      POSTGRES_PASSWORD: password
      POSTGRES_DB: json_share_app
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


